// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const defaults = {
  kind: "deepternary",
  input_mode: "binary_poses",
  mechanism: "protac",
  partner_a_name: "Recruiting partner",
  partner_b_name: "Target protein",
  partner_a_chain: "A",
  partner_b_chain: "B",
  samples: 3,
  attempt_budget: 12,
  wall_seconds: 600,
  arm_a_map: [],
  arm_b_map: [],
  binding_region_a: [],
  binding_region_b: [],
  ligand_correction: true,
};
