// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const constraintSchema = {
  $defs: {
    CoordinateFrame: {
      additionalProperties: false,
      properties: {
        reference: {
          $ref: "#/$defs/MoleculeRef",
        },
        basis: {
          enum: ["reference_coordinates", "user_confirmed_alignment"],
          title: "Basis",
          type: "string",
        },
        unit: {
          const: "angstrom",
          default: "angstrom",
          title: "Unit",
          type: "string",
        },
      },
      required: ["reference", "basis"],
      title: "CoordinateFrame",
      type: "object",
    },
    FixedRegionCondition: {
      additionalProperties: false,
      properties: {
        id: {
          format: "uuid",
          title: "Id",
          type: "string",
        },
        label: {
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Label",
          type: "string",
        },
        strength: {
          default: "hard",
          enum: ["hard", "soft"],
          title: "Strength",
          type: "string",
        },
        weight: {
          anyOf: [
            {
              exclusiveMinimum: 0,
              maximum: 1000,
              type: "number",
            },
            {
              type: "null",
            },
          ],
          default: null,
          title: "Weight",
        },
        scope: {
          default: "subject",
          enum: ["subject", "target_a", "target_b", "assembly"],
          title: "Scope",
          type: "string",
        },
        source: {
          default: "user_selection",
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Source",
          type: "string",
        },
        kind: {
          const: "fixed_region",
          title: "Kind",
          type: "string",
        },
        phase: {
          const: "sampling",
          default: "sampling",
          title: "Phase",
          type: "string",
        },
        region_id: {
          format: "uuid",
          title: "Region Id",
          type: "string",
        },
        region_name: {
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Region Name",
          type: "string",
        },
        validator: {
          const: "exact_native_indices",
          default: "exact_native_indices",
          title: "Validator",
          type: "string",
        },
      },
      required: ["id", "label", "kind", "region_id", "region_name"],
      title: "FixedRegionCondition",
      type: "object",
    },
    MoleculeRef: {
      additionalProperties: false,
      properties: {
        asset_id: {
          format: "uuid",
          title: "Asset Id",
          type: "string",
        },
        sha256: {
          pattern: "^[a-f0-9]{64}$",
          title: "Sha256",
          type: "string",
        },
        record: {
          default: 0,
          maximum: 499,
          minimum: 0,
          title: "Record",
          type: "integer",
        },
        conformer: {
          default: 0,
          maximum: 999,
          minimum: 0,
          title: "Conformer",
          type: "integer",
        },
        version_id: {
          anyOf: [
            {
              format: "uuid",
              type: "string",
            },
            {
              type: "null",
            },
          ],
          default: null,
          title: "Version Id",
        },
      },
      required: ["asset_id", "sha256"],
      title: "MoleculeRef",
      type: "object",
    },
    SearchBox: {
      additionalProperties: false,
      properties: {
        center: {
          maxItems: 3,
          minItems: 3,
          prefixItems: [
            {
              maximum: 100000,
              minimum: -100000,
              type: "number",
            },
            {
              maximum: 100000,
              minimum: -100000,
              type: "number",
            },
            {
              maximum: 100000,
              minimum: -100000,
              type: "number",
            },
          ],
          title: "Center",
          type: "array",
        },
        size: {
          maxItems: 3,
          minItems: 3,
          prefixItems: [
            {
              maximum: 100,
              minimum: 4,
              type: "number",
            },
            {
              maximum: 100,
              minimum: 4,
              type: "number",
            },
            {
              maximum: 100,
              minimum: 4,
              type: "number",
            },
          ],
          title: "Size",
          type: "array",
        },
        unit: {
          const: "angstrom",
          default: "angstrom",
          title: "Unit",
          type: "string",
        },
      },
      required: ["center", "size"],
      title: "SearchBox",
      type: "object",
    },
    SearchBoxCondition: {
      additionalProperties: false,
      properties: {
        id: {
          format: "uuid",
          title: "Id",
          type: "string",
        },
        label: {
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Label",
          type: "string",
        },
        strength: {
          default: "hard",
          enum: ["hard", "soft"],
          title: "Strength",
          type: "string",
        },
        weight: {
          anyOf: [
            {
              exclusiveMinimum: 0,
              maximum: 1000,
              type: "number",
            },
            {
              type: "null",
            },
          ],
          default: null,
          title: "Weight",
        },
        scope: {
          default: "target_a",
          enum: ["target_a", "target_b", "assembly"],
          title: "Scope",
          type: "string",
        },
        source: {
          default: "user_selection",
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Source",
          type: "string",
        },
        kind: {
          const: "search_box",
          title: "Kind",
          type: "string",
        },
        phase: {
          const: "input",
          default: "input",
          title: "Phase",
          type: "string",
        },
        box: {
          $ref: "#/$defs/SearchBox",
        },
        validator: {
          const: "exact_native_search_box",
          default: "exact_native_search_box",
          title: "Validator",
          type: "string",
        },
      },
      required: ["id", "label", "kind", "box"],
      title: "SearchBoxCondition",
      type: "object",
    },
    SpatialBoundsCondition: {
      additionalProperties: false,
      properties: {
        id: {
          format: "uuid",
          title: "Id",
          type: "string",
        },
        label: {
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Label",
          type: "string",
        },
        strength: {
          default: "hard",
          enum: ["hard", "soft"],
          title: "Strength",
          type: "string",
        },
        weight: {
          anyOf: [
            {
              exclusiveMinimum: 0,
              maximum: 1000,
              type: "number",
            },
            {
              type: "null",
            },
          ],
          default: null,
          title: "Weight",
        },
        scope: {
          default: "target_a",
          enum: ["target_a", "target_b", "assembly"],
          title: "Scope",
          type: "string",
        },
        source: {
          default: "user_selection",
          maxLength: 120,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f]+$",
          title: "Source",
          type: "string",
        },
        kind: {
          const: "spatial_bounds",
          title: "Kind",
          type: "string",
        },
        phase: {
          const: "result",
          default: "result",
          title: "Phase",
          type: "string",
        },
        selection: {
          default: "heavy_atom_centroid",
          enum: ["heavy_atom_centroid", "all_heavy_atoms"],
          title: "Selection",
          type: "string",
        },
        box: {
          $ref: "#/$defs/SearchBox",
        },
        tolerance_angstrom: {
          default: 0.001,
          maximum: 0.1,
          minimum: 0,
          title: "Tolerance Angstrom",
          type: "number",
        },
        validator: {
          const: "rdkit_receptor_bounds_v1",
          default: "rdkit_receptor_bounds_v1",
          title: "Validator",
          type: "string",
        },
      },
      required: ["id", "label", "kind", "box"],
      title: "SpatialBoundsCondition",
      type: "object",
    },
  },
  additionalProperties: false,
  properties: {
    schema_version: {
      const: 1,
      default: 1,
      title: "Schema Version",
      type: "integer",
    },
    name: {
      maxLength: 120,
      minLength: 1,
      pattern: "^[^\\x00-\\x1f]+$",
      title: "Name",
      type: "string",
    },
    subject: {
      $ref: "#/$defs/MoleculeRef",
    },
    frame: {
      anyOf: [
        {
          $ref: "#/$defs/CoordinateFrame",
        },
        {
          type: "null",
        },
      ],
      default: null,
    },
    parent_id: {
      anyOf: [
        {
          format: "uuid",
          type: "string",
        },
        {
          type: "null",
        },
      ],
      default: null,
      title: "Parent Id",
    },
    conditions: {
      items: {
        discriminator: {
          mapping: {
            fixed_region: "#/$defs/FixedRegionCondition",
            search_box: "#/$defs/SearchBoxCondition",
            spatial_bounds: "#/$defs/SpatialBoundsCondition",
          },
          propertyName: "kind",
        },
        oneOf: [
          {
            $ref: "#/$defs/FixedRegionCondition",
          },
          {
            $ref: "#/$defs/SearchBoxCondition",
          },
          {
            $ref: "#/$defs/SpatialBoundsCondition",
          },
        ],
      },
      maxItems: 32,
      minItems: 1,
      title: "Conditions",
      type: "array",
    },
  },
  required: ["name", "subject", "conditions"],
  title: "ConstraintSet",
  type: "object",
} as const;
export const outputBoundsDefaults = {
  tolerance_angstrom: 0.001,
  strength: "hard",
  weight: 1,
} as const;
