// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const defaults = {
  maximum_center_distance: 8.0,
  minimum_jaccard: 0.25,
  minimum_mapping_coverage: 0.7,
  minimum_shared_residues: 2,
};
export const schema = {
  additionalProperties: false,
  properties: {
    maximum_center_distance: {
      default: 8,
      maximum: 30,
      minimum: 0.1,
      title: "Maximum Center Distance",
      type: "number",
    },
    minimum_jaccard: {
      default: 0.25,
      maximum: 1,
      minimum: 0.01,
      title: "Minimum Jaccard",
      type: "number",
    },
    minimum_mapping_coverage: {
      default: 0.7,
      maximum: 1,
      minimum: 0.1,
      title: "Minimum Mapping Coverage",
      type: "number",
    },
    minimum_shared_residues: {
      default: 2,
      maximum: 100,
      minimum: 1,
      title: "Minimum Shared Residues",
      type: "integer",
    },
  },
  title: "SiteOptions",
  type: "object",
} as const;
