// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const channelDefaults = {
  model_index: 0,
  context_chains: [],
  remove_starting_ligands: true,
  alternate: "A",
  probe_radius_angstrom: 0.9,
  shell_radius_angstrom: 5.0,
  shell_depth_angstrom: 4.0,
  maximum_start_displacement_angstrom: 3.0,
  profile_step_angstrom: 0.5,
  maximum_candidates: 500,
  cpu: 2,
  memory_mib: 2048,
  timeout_seconds: 180,
};
