// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const humanizationDefaults = {
  mode: "evaluate",
  format: "conventional",
  iterations: 1,
  max_mutations: 0,
  cpu: 1,
  memory_mib: 4096,
} as const;
export const humanizationVersions = {
  sapiens: "1.1.0",
  anarcii: "2.0.8",
  promb: "1.0.2",
  torch: "2.8.0+cpu",
  transformers: "4.57.6",
  safetensors: "0.7.0",
  numpy: "2.2.6",
  pandas: "2.3.3",
  scipy: "1.16.2",
} as const;
export const humanizationMaxRecords = 20;
