// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const admetDefaults = {
  view: "all",
  cpu: 1,
  memory_mib: 4096,
} as const;
export const admetVersions = {
  "admet-ai": "2.0.1",
  chemprop: "2.3.1",
  torch: "2.8.0+cpu",
  rdkit: "2026.3.6",
  numpy: "2.2.6",
  pandas: "2.3.3",
  lightning: "2.6.1",
} as const;
export const admetLimits = {
  maxRecords: 50,
  maxHeavyAtoms: 256,
  maxInputBytes: 8388608,
} as const;
