"""Real analysis, machine-readable candidates, and downloadable reports."""

import csv
import html
import io
import json
from typing import Literal
from uuid import UUID

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import HTMLResponse, Response

from .analysis import AnalysisService
from .confidence import confidence_view
from .engine import DockerEngine, Engine
from .models import Status
from .settings import Settings
from .store import Store


def register_science(app: FastAPI, store: Store, engine: Engine, settings: Settings):
    service = (
        AnalysisService(engine, settings.state_dir / "jobs")
        if isinstance(engine, DockerEngine)
        else None
    )

    async def result(job_id: UUID):
        job = store.get(str(job_id))
        if not job:
            raise HTTPException(404, "Task not found.")
        if job.status != Status.SUCCEEDED or job.request.operation != "predict":
            raise HTTPException(409, "Analysis requires a completed prediction.")
        if service is None:
            raise HTTPException(503, "Scientific analysis requires the Docker runtime.")
        try:
            return job, await service.get(job)
        except (OSError, ValueError, RuntimeError, TimeoutError) as error:
            raise HTTPException(
                503,
                "Analysis could not complete. Prediction files are preserved; "
                "check the task analysis log.",
            ) from error

    @app.get("/api/jobs/{job_id}/analysis")
    async def analysis(job_id: UUID):
        _, data = await result(job_id)
        return data

    @app.get("/api/jobs/{job_id}/confidence")
    async def confidence(
        job_id: UUID,
        candidate: str = Query(min_length=1, max_length=100),
        metric: Literal["pae", "pde", "contacts"] = "pae",
    ):
        _, data = await result(job_id)
        selected = next((c for c in data["candidates"] if c["id"] == candidate), None)
        if selected is None:
            raise HTTPException(404, "Candidate not found.")
        try:
            return confidence_view(
                settings.state_dir / "jobs" / str(job_id) / "output", selected["artifact"], metric
            )
        except FileNotFoundError as exc:
            raise HTTPException(
                404,
                "This prediction has no atom-level confidence artifact. "
                "Enable it in expert parameters for a new run.",
            ) from exc
        except ValueError as exc:
            raise HTTPException(422, str(exc)) from exc

    @app.get("/api/jobs/{job_id}/candidates.csv")
    async def candidates_csv(job_id: UUID):
        _, data = await result(job_id)
        buffer = io.StringIO()
        fields = [
            "id",
            "ranking_score",
            "plddt",
            "ptm",
            "iptm",
            "rmsd_to_first",
            "atom_count",
        ]
        writer = csv.DictWriter(buffer, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(data["candidates"])
        return Response(
            buffer.getvalue(),
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{job_id}-candidates.csv"'},
        )

    @app.get("/api/jobs/{job_id}/report")
    async def report(job_id: UUID):
        job, data = await result(job_id)
        escape = html.escape
        rows = "".join(
            f"<tr><td>{escape(candidate['id'])}</td><td>{candidate['ranking_score']}</td><td>{candidate['plddt']}</td><td>{candidate['iptm']}</td><td>{candidate['atom_count']}</td></tr>"
            for candidate in data["candidates"]
        )
        page = f"""<!doctype html><html lang="en"><meta charset="utf-8">
            <title>{escape(job.request.name)} — OpenDDE report</title>
            <h1>{escape(job.request.name)}</h1><p>Task: {job.id}</p>
            <p>Created: {escape(job.created_at)}; completed: {escape(job.finished_at or "")}</p>
            <p>Structural predictions and computational descriptors are not measured potency.</p>
            <table border="1" cellpadding="8"><tr><th>Candidate</th><th>Ranking score</th>
            <th>pLDDT</th><th>ipTM</th><th>Atoms</th></tr>{rows}</table>
            <h2>Molecular descriptors (RDKit)</h2>
            <pre>{escape(json.dumps(data["ligands"], indent=2))}</pre>
            <h2>Metric definitions</h2>
            <pre>{escape(json.dumps(data["metric_notes"], indent=2))}</pre>
            <h2>Reproducible input</h2><pre>{escape(job.request.model_dump_json(indent=2))}</pre>
            <p>Generated by the independent MIT OpenDDE Workbench. Engine: OpenDDE (Apache-2.0).</p>
            </html>"""
        return HTMLResponse(
            page, headers={"Content-Disposition": f'attachment; filename="{job_id}-report.html"'}
        )
