// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const roles = [
  {
    id: "fixed_core",
    label: ["固定核心", "Fixed core"],
    help: [
      "局部重设计中保持的原子。只有显式提交固定原子才会影响生成。",
      "Atoms retained in inpainting; generation changes only when fixed atoms are submitted.",
    ],
  },
  {
    id: "binder_a",
    label: ["结合端 A", "Binder A"],
    help: [
      "标记第一结合端；区域标签本身不证明结合。",
      "Annotate the first binder; a label does not prove binding.",
    ],
  },
  {
    id: "binder_b",
    label: ["结合端 B", "Binder B"],
    help: [
      "标记第二结合端；可与其他区域重叠。",
      "Annotate the second binder; regions may overlap.",
    ],
  },
  {
    id: "linker",
    label: ["连接区", "Linker"],
    help: [
      "完整分子中连接各端的逻辑区域，不切断键。",
      "A logical connecting region in the full molecule; no bonds are cut.",
    ],
  },
  {
    id: "payload",
    label: ["载荷", "Payload"],
    help: [
      "标记载荷部分，保持完整分子与原始文件。",
      "Annotate a payload while retaining the full molecule and file.",
    ],
  },
  {
    id: "mutable",
    label: ["可修改区域", "Mutable region"],
    help: [
      "标注允许调整的区域；实际设计仍以提交的固定原子与支持参数为准。",
      "Annotate regions allowed to change; actual design follows submitted fixed atoms and supported parameters.",
    ],
  },
  {
    id: "custom",
    label: ["自定义区域", "Custom region"],
    help: ["命名一个需要复用的原子集合。", "Name an atom selection for reuse."],
  },
] as const;
