// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const methodChoices = [
  {
    id: "complex_structure",
    label: ["复合物结构预测", "Complex structure prediction"],
    options: [
      {
        id: "predict",
        label: "OpenDDE",
        note: [
          "标准与抗体专用模型；支持范围以当前表单为准。",
          "Standard and antibody-specific checkpoints; use the current form's supported inputs.",
        ],
      },
      {
        id: "boltz.predict",
        label: "Boltz-2",
        note: [
          "复合物结构与可选亲和力模型；参数和置信度不能与其他方法直接混用。",
          "Complex structures and optional model affinity; parameters and confidence are method-specific.",
        ],
      },
    ],
    default: "predict",
    default_basis: [
      "按任务用途保留当前默认；新方法需匹配输入比较后再替换。",
      "Keep the current task default until matched-input comparison supports replacement.",
    ],
  },
  {
    id: "structure_guided_sequence",
    label: ["结构引导序列设计", "Structure-guided sequence design"],
    options: [
      {
        id: "mpnn",
        label: "SolubleMPNN",
        note: [
          "适合可溶性蛋白的结构引导序列提案。",
          "Structure-guided sequence proposals for soluble proteins.",
        ],
      },
      {
        id: "ligandmpnn.design",
        label: "LigandMPNN",
        note: [
          "在保留的配体和结构环境中设计蛋白序列。",
          "Design protein sequences in retained ligand and structural context.",
        ],
      },
    ],
    default: "mpnn",
    default_basis: [
      "按任务用途保留当前默认；新方法需匹配输入比较后再替换。",
      "Keep the current task default until matched-input comparison supports replacement.",
    ],
  },
  {
    id: "molecular_dynamics",
    label: ["分子动力学", "Molecular dynamics"],
    options: [
      {
        id: "openmm.dynamics",
        label: "OpenMM",
        note: [
          "当前默认；保留原生最小化、显式水采样和历史结果。",
          "Current default: native minimization, explicit-water sampling and retained results.",
        ],
      },
      {
        id: "gromacs.dynamics",
        label: "GROMACS",
        note: [
          "独立 CPU/CUDA 环境；原生轨迹与检查点；科学验收待服务器执行。",
          "Independent CPU/CUDA environment, native trajectories and checkpoints; scientific acceptance requires the target server.",
        ],
      },
    ],
    default: "openmm.dynamics",
    default_basis: [
      "按任务用途保留当前默认；新方法需匹配输入比较后再替换。",
      "Keep the current task default until matched-input comparison supports replacement.",
    ],
  },
  {
    id: "method.caver.paths",
    label: ["口袋通道与瓶颈", "Pocket channels and bottlenecks"],
    default: "caver.paths",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "caver.paths",
        label: "CAVER 3.0.2",
        note: [
          "点选起始区域，探索通向溶剂的静态几何路径和最窄位置。",
          "Select a starting region and explore static solvent paths and bottlenecks.",
        ],
      },
    ],
  },
  {
    id: "method.openfe.rbfe",
    label: ["FEP 结合自由能", "FEP binding free energy"],
    default: "openfe.rbfe",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "openfe.rbfe",
        label: "OpenFE",
        note: [
          "构建同系列分子的相对自由能网络，检查误差与收敛。",
          "Plan congeneric free-energy networks and inspect uncertainty and convergence.",
        ],
      },
    ],
  },
  {
    id: "method.deepternary.model",
    label: ["三元复合物建模", "Ternary complex modeling"],
    default: "deepternary.model",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "deepternary.model",
        label: "DeepTernary",
        note: [
          "比较降解剂、RIPTAC、分子胶与诱导邻近分子的完整装配假设。",
          "Compare complete PROTAC, RIPTAC, molecular-glue and proximity assemblies.",
        ],
      },
    ],
  },
  {
    id: "method.reinvent.design",
    label: ["类似物与多目标分子设计", "Analogues and molecular optimization"],
    default: "reinvent.design",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "reinvent.design",
        label: "REINVENT4",
        note: [
          "选择类似物、R 基、连接子或性质优化方案。",
          "Choose analogues, R-groups, linkers or property optimization.",
        ],
      },
    ],
  },
  {
    id: "method.boltzgen.design",
    label: ["结合蛋白、肽与抗体设计", "Protein, peptide and antibody design"],
    default: "boltzgen.design",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "boltzgen.design",
        label: "BoltzGen",
        note: [
          "按药物形式选择设计方案，比较原生结构与界面结果。",
          "Choose a design modality and compare native structural results.",
        ],
      },
    ],
  },
  {
    id: "method.openmm.refine",
    label: ["结构准备与约束优化", "Structure preparation and refinement"],
    default: "openmm.refine",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "openmm.refine",
        label: "OpenMM",
        note: [
          "补齐已解析残基的原子并优化结构，保留原始文件。",
          "Prepare resolved atoms and refine structures while preserving originals.",
        ],
      },
    ],
  },
  {
    id: "method.apbs.potential",
    label: ["蛋白表面电势", "Protein electrostatic surface"],
    default: "apbs.potential",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "apbs.potential",
        label: "APBS",
        note: [
          "在指定 pH 和盐浓度下计算电势并下载三维网格。",
          "Calculate potential at selected pH/salt conditions and export the grid.",
        ],
      },
    ],
  },
  {
    id: "method.chemprop.train",
    label: ["建立实验数据性质模型", "Train a property model"],
    default: "chemprop.train",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "chemprop.train",
        label: "Chemprop",
        note: [
          "从带标签的分子库训练模型，保留骨架划分验证与原始单位。",
          "Train from labeled molecular libraries with scaffold-split validation.",
        ],
      },
    ],
  },
  {
    id: "method.chemprop.predict",
    label: ["用研究模型预测性质", "Predict with a research model"],
    default: "chemprop.predict",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "chemprop.predict",
        label: "Chemprop",
        note: [
          "选择已训练模型并预测新分子，保留模型版本与单位。",
          "Choose a trained model to predict new molecules with original units.",
        ],
      },
    ],
  },
  {
    id: "method.plip.profile",
    label: ["结合相互作用与三维标注", "Interactions and 3D annotations"],
    default: "plip.profile",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "plip.profile",
        label: "PLIP",
        note: [
          "显示原生化学相互作用类型、关键残基和真实距离。",
          "Display native interaction types, residues and coordinate distances.",
        ],
      },
    ],
  },
  {
    id: "method.library.import",
    label: ["分子库管理", "Compound libraries"],
    default: "library.import",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "library.import",
        label: "RDKit",
        note: [
          "导入供应商文件，保留货号、结构与每条失败记录。",
          "Import supplier files with original IDs, chemistry and rejected records.",
        ],
      },
    ],
  },
  {
    id: "method.library.select",
    label: ["提取候选分子", "Extract candidates"],
    default: "library.select",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "library.select",
        label: "RDKit",
        note: [
          "从确切分子库选择成员，生成可用于后续任务的候选集。",
          "Select exact library members and prepare a reusable candidate set.",
        ],
      },
    ],
  },
  {
    id: "method.drugclip.index",
    label: ["建立快速筛选库", "Prepare a screening index"],
    default: "drugclip.index",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "drugclip.index",
        label: "Pocket–molecule joint retrieval",
        note: [
          "使用官方六折模型编码分子，后续筛选直接使用索引。",
          "Encode molecules with the official six-fold model for reusable screening.",
        ],
      },
    ],
  },
  {
    id: "method.drugclip.screen",
    label: ["高通量筛选", "High-throughput screening"],
    default: "drugclip.screen",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "drugclip.screen",
        label: "Pocket–molecule joint retrieval",
        note: [
          "选择靶点口袋和分子库，快速寻找候选；仅非商业科研。",
          "Search molecular libraries for an observed target pocket; noncommercial research.",
        ],
      },
    ],
  },
  {
    id: "method.screening.dock",
    label: ["候选批量对接", "Dock shortlisted candidates"],
    default: "screening.dock",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "screening.dock",
        label: "GNINA",
        note: [
          "计算真实结合姿势，保留每个候选的得分与失败原因。",
          "Compute real binding poses with candidate scores and explicit failures.",
        ],
      },
    ],
  },
  {
    id: "method.del.library",
    label: ["DEL 库定义", "DEL library definition"],
    default: "del.library",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.library",
        label: "DELi",
        note: [
          "检查周期、砌块、编码冲突与已有化学规则。",
          "Review cycles, building blocks, barcode ambiguity and supplied chemistry.",
        ],
      },
    ],
  },
  {
    id: "method.del.enumerate",
    label: ["DEL 成员结构", "DEL member structures"],
    default: "del.enumerate",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.enumerate",
        label: "DELi",
        note: [
          "按核实的库规则解析成员，支持候选预览和大库导出。",
          "Resolve structures using supplied library rules; preview or export members.",
        ],
      },
    ],
  },
  {
    id: "method.del.decode",
    label: ["测序解码", "Decode selection reads"],
    default: "del.decode",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.decode",
        label: "DELi",
        note: [
          "检查真实读段、匹配条码，保留歧义及未匹配原因。",
          "Inspect reads and call barcodes with ambiguity and rejection evidence.",
        ],
      },
    ],
  },
  {
    id: "method.del.count",
    label: ["UMI 与计数", "UMI and counts"],
    default: "del.count",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.count",
        label: "DELi",
        note: [
          "在样本和化合物内去重，分别保留读段和 UMI 计数。",
          "Count UMIs within each sample and compound; retain raw-read evidence.",
        ],
      },
    ],
  },
  {
    id: "method.del.analyze",
    label: ["DEL 富集与命中", "DEL enrichment and hits"],
    default: "del.analyze",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.analyze",
        label: "DELi",
        note: [
          "按实验分组比较富集、对照、重复一致性与候选证据。",
          "Compare enrichment, references, replicates and candidate evidence.",
        ],
      },
    ],
  },
  {
    id: "method.del.series",
    label: ["砌块与系列探索", "Building blocks and series"],
    default: "del.series",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.series",
        label: "DELi",
        note: [
          "探索单砌块、双砌块组合和真实观察到的系列覆盖。",
          "Explore mono-/disynthon evidence and observed series coverage.",
        ],
      },
    ],
  },
  {
    id: "method.del.model",
    label: ["DEL 研究模型", "DEL research models"],
    default: "del.model",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.model",
        label: "DELi",
        note: [
          "使用独立砌块留出评估分子富集基线，不预测实测亲和力。",
          "Evaluate an enrichment baseline using independent cycle holdout; not affinity.",
        ],
      },
    ],
  },
  {
    id: "method.del.candidates",
    label: ["DEL 候选交接", "DEL candidate handoff"],
    default: "del.candidates",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.candidates",
        label: "DELi",
        note: [
          "解析所选命中结构，交给性质分析和对接任务。",
          "Resolve selected hit structures for property evaluation and docking.",
        ],
      },
    ],
  },
  {
    id: "method.del.followup",
    label: ["后续实验回填", "Follow-up measurements"],
    default: "del.followup",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "del.followup",
        label: "DELi",
        note: [
          "登记用户提供的 KD、IC50 等测量，与计算富集分开。",
          "Record user-supplied KD/IC50 measurements separately from enrichment.",
        ],
      },
    ],
  },
  {
    id: "method.antibody.humanize",
    label: [
      "抗体人源参考与框架优化",
      "Antibody human reference and framework proposals",
    ],
    default: "antibody.humanize",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "antibody.humanize",
        label: "Sapiens / ANARCII / Promb",
        note: [
          "评估确切的抗体可变域，保留 CDR，修改建议保存为独立序列版本。",
          "Evaluate exact variable regions and preserve CDRs; save changed proposals as new versions.",
        ],
      },
    ],
  },
  {
    id: "method.admet.predict",
    label: ["性质与早期安全性预测", "ADMET and early safety predictions"],
    default: "admet.predict",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "admet.predict",
        label: "ADMET-AI / Chemprop",
        note: [
          "独立模型预测 41 个终点，保留原始分子、单位、物种与适用范围。",
          "Predict 41 native endpoints with original molecules, units, species and scope.",
        ],
      },
    ],
  },
  {
    id: "method.posebusters.check",
    label: ["构象与姿势质控", "Conformation and pose quality"],
    default: "posebusters.check",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "posebusters.check",
        label: "PoseBusters",
        note: [
          "检查分子几何、蛋白内碰撞和参考姿势；保留未能计算的项目。",
          "Check molecular geometry, protein clashes and reference poses; retain missing checks.",
        ],
      },
    ],
  },
  {
    id: "method.antibody.number",
    label: ["抗体编号与 CDR 标注", "Antibody numbering and CDR annotation"],
    default: "antibody.number",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "antibody.number",
        label: "ANARCII",
        note: [
          "识别抗体链与结构域，保留原始序列位置和 IMGT 编号。",
          "Identify antibody chains/domains with original sequence positions and IMGT numbering.",
        ],
      },
    ],
  },
  {
    id: "method.chemistry.screen",
    label: ["分子库与早期筛选", "Library and early molecular selection"],
    default: "chemistry.screen",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "chemistry.screen",
        label: "RDKit",
        note: [
          "结构风险提示、骨架代表选择、相似性与分子库筛选。",
          "Structural alerts, scaffold representatives, similarity and library selection.",
        ],
      },
    ],
  },
  {
    id: "method.biopython.prepare",
    label: ["结构准备", "Prepare structure"],
    default: "biopython.prepare",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "biopython.prepare",
        label: "Biopython",
        note: [
          "选择模型、链、水和其他成分，保存新的结构版本。",
          "Select observed model, chains, water and components; save a new version.",
        ],
      },
    ],
  },
  {
    id: "method.biopython.exposure",
    label: ["区域暴露与埋藏", "Region exposure and burial"],
    default: "biopython.exposure",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "biopython.exposure",
        label: "Biopython Shrake-Rupley",
        note: [
          "点选配体或残基，比较孤立区域与整体结构中的溶剂可接触面积。",
          "Select ligands or residues and compare solvent accessibility in isolation and in the provided assembly.",
        ],
      },
    ],
  },
  {
    id: "method.discovery.import",
    label: [
      "导入参考结构与化合物",
      "Import reference structures and compounds",
    ],
    default: "discovery.import",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "discovery.import",
        label: "RCSB PDB / ChEMBL",
        note: [
          "从 PDB/ChEMBL 获取原始记录，保留证据与确切资产版本。",
          "Retrieve original PDB/ChEMBL records with evidence and exact asset versions.",
        ],
      },
    ],
  },
  {
    id: "method.discovery.target",
    label: ["靶点证据与研究材料", "Target evidence and materials"],
    default: "discovery.target",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "discovery.target",
        label: "Open Targets / UniProt / ChEMBL",
        note: [
          "查询疾病关联、干预线索、序列、结构索引和已有实测活性。",
          "Retrieve disease associations, tractability, sequence, structure references and measured activities.",
        ],
      },
    ],
  },
  {
    id: "method.discovery.disease",
    label: ["从疾病寻找靶点", "Find targets for a disease"],
    default: "discovery.disease",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "discovery.disease",
        label: "Open Targets / UniProt / ChEMBL",
        note: [
          "查看人类靶点关联及来源，选择下一步研究对象。",
          "Review human target associations and provenance before selecting a research target.",
        ],
      },
    ],
  },
  {
    id: "method.properties",
    label: ["计算小分子性质", "Calculate molecular properties"],
    default: "properties",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "properties",
        label: "RDKit",
        note: [
          "SMILES 或 SDF 批量计算 MW、LogP、TPSA、QED、SA、氢键与柔性指标。",
          "Batch descriptors from SMILES or SDF: MW, LogP, TPSA, QED, SA, hydrogen-bond counts and flexibility.",
        ],
      },
    ],
  },
  {
    id: "method.campaign",
    label: ["抗体设计与 CDR 优化", "Antibody design and CDR optimization"],
    default: "campaign",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "campaign",
        label: "Harness + LLM",
        note: [
          "VHH、scFv、VH/VL；多轮候选生成、折叠评分、筛选与反思。",
          "VHH, scFv and VH/VL; iterative generation, folding, ranking and reflection.",
        ],
      },
    ],
  },
  {
    id: "method.esm",
    label: ["蛋白序列评分", "Score protein sequences"],
    default: "esm",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "esm",
        label: "Harness / ESM2",
        note: [
          "使用 ESM2 对现有序列评分，辅助候选比较。",
          "ESM2 scores for comparing existing sequences.",
        ],
      },
    ],
  },
  {
    id: "method.esm2",
    label: ["ESM2 引导序列提案", "ESM2-guided sequence proposals"],
    default: "esm2",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "esm2",
        label: "Harness / ESM2",
        note: [
          "指定可变位置，生成有模型评分支持的序列提案。",
          "Propose sequences at selected mutable positions with model scores.",
        ],
      },
    ],
  },
  {
    id: "method.fold",
    label: ["结合体折叠与界面评分", "Binder folding and interface scoring"],
    default: "fold",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "fold",
        label: "Harness / OpenDDE",
        note: [
          "预测结合体复合物，比较结构置信度与界面指标。",
          "Predict binder complexes and compare structural confidence and interface metrics.",
        ],
      },
    ],
  },
  {
    id: "method.epitope",
    label: ["表位与热点接触", "Epitope and hotspot contacts"],
    default: "epitope",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "epitope",
        label: "Harness",
        note: [
          "分析抗体、抗原链及 CDR 对目标区域的接触。",
          "Inspect contacts between antibody CDRs and antigen regions.",
        ],
      },
    ],
  },
  {
    id: "method.structure",
    label: ["复合物相互作用分析", "Complex interaction analysis"],
    default: "structure",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "structure",
        label: "Harness / PLIP",
        note: [
          "PLIP 结构分析，可比较最多三个候选。",
          "PLIP structural interaction analysis for up to three candidates.",
        ],
      },
    ],
  },
  {
    id: "method.rmsd",
    label: ["对齐目标后比较结合姿势", "Compare target-aligned binding poses"],
    default: "rmsd",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "rmsd",
        label: "Harness",
        note: [
          "对齐目标链后计算结合链 RMSD。",
          "Align target chains and calculate binder RMSD.",
        ],
      },
    ],
  },
  {
    id: "method.evolution",
    label: ["候选进化树", "Candidate evolution tree"],
    default: "evolution",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "evolution",
        label: "Harness",
        note: [
          "从候选历史中查看谱系和目标分数变化。",
          "Review lineages and objective changes from candidate history.",
        ],
      },
    ],
  },
  {
    id: "method.compare",
    label: ["比较两个候选集", "Compare candidate populations"],
    default: "compare",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "compare",
        label: "Harness",
        note: [
          "比较两次设计的目标值、最佳候选与候选重合情况。",
          "Compare objectives, leading candidates and overlap across two design runs.",
        ],
      },
    ],
  },
  {
    id: "method.protrek-sequence",
    label: ["按蛋白序列检索", "Search by protein sequence"],
    default: "protrek-sequence",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "protrek-sequence",
        label: "Harness / ProTrek",
        note: [
          "连接配置的 ProTrek 服务，检索相似蛋白。",
          "Find similar proteins through the configured ProTrek service.",
        ],
      },
    ],
  },
  {
    id: "method.protrek-structure",
    label: ["按蛋白结构检索", "Search by protein structure"],
    default: "protrek-structure",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "protrek-structure",
        label: "Harness / ProTrek",
        note: [
          "选择结构和链，使用 ProTrek 检索。",
          "Search ProTrek using a structure and chain.",
        ],
      },
    ],
  },
  {
    id: "method.target-msa",
    label: ["准备抗体设计靶标 MSA", "Prepare target MSA for design"],
    default: "target-msa",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "target-msa",
        label: "Harness",
        note: [
          "搜索靶标的相似序列，查看多序列比对的规模。",
          "Search target homologs and inspect multiple-sequence alignment depth.",
        ],
      },
    ],
  },
  {
    id: "method.features",
    label: ["准备 MSA 与模板", "Prepare MSAs and templates"],
    default: "features",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "features",
        label: "OpenDDE",
        note: [
          "为结构预测准备多序列比对和参考结构模板。",
          "Prepare sequence alignments and structural templates for prediction.",
        ],
      },
    ],
  },
  {
    id: "method.import",
    label: ["导入结构与批量任务", "Import structures and batch tasks"],
    default: "import",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "import",
        label: "OpenDDE",
        note: [
          "PDB/CIF 转输入；导入原生 JSON，审阅后单次或批量提交。",
          "Convert PDB/CIF, import native JSON, review and submit single or batch tasks.",
        ],
      },
    ],
  },
  {
    id: "method.resources",
    label: ["模型、数据库与环境检查", "Models, databases and diagnostics"],
    default: "resources",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "resources",
        label: "OpenDDE",
        note: [
          "查看依赖状态，安装原生资源，运行 doctor。",
          "Inspect dependencies, install native resources and run doctor.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.generate",
    label: ["口袋条件分子生成", "Pocket-conditioned molecule generation"],
    default: "diffsbdd.generate",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.generate",
        label: "DiffSBDD",
        note: [
          "围绕选定受体口袋，生成新的小分子候选。",
          "Generate new small-molecule candidates for a selected receptor pocket.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.inpaint",
    label: ["局部重设计", "Local molecule inpainting"],
    default: "diffsbdd.inpaint",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.inpaint",
        label: "DiffSBDD",
        note: [
          "明确固定原子、保留键和三维初始分子。",
          "Requires fixed atoms, retained bonds and an aligned 3D initial molecule.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.diversify",
    label: ["分子多样化", "Diversify molecules"],
    default: "diffsbdd.diversify",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.diversify",
        label: "DiffSBDD",
        note: [
          "在兼容条件模型下处理三维初始分子。",
          "Use a 3D initial molecule and a compatible conditional model.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.optimize",
    label: ["分子优化", "Optimize molecules"],
    default: "diffsbdd.optimize",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.optimize",
        label: "DiffSBDD",
        note: [
          "选择类药性或合成难度目标，探索新的分子候选。",
          "Explore molecular candidates using drug-likeness or synthesis-difficulty objectives.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.pocket",
    label: ["口袋检查", "Inspect pockets"],
    default: "diffsbdd.pocket",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.pocket",
        label: "DiffSBDD",
        note: [
          "查看所选口袋的位置和包含的残基。",
          "Inspect the selected pocket and its residues.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.prepare",
    label: ["准备受体结构", "Prepare receptors"],
    default: "diffsbdd.prepare",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.prepare",
        label: "DiffSBDD",
        note: [
          "按明确链、水、配体和氢处理选择生成新结果。",
          "Prepare a new result using explicit chain, water, ligand and hydrogen choices.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.interactions",
    label: ["分子相互作用", "Molecular interactions"],
    default: "diffsbdd.interactions",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.interactions",
        label: "DiffSBDD",
        note: [
          "使用真实 ProLIF 规则和输入结构。",
          "Use actual ProLIF rules and input structures.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.properties",
    label: ["候选描述符", "Candidate descriptors"],
    default: "diffsbdd.properties",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.properties",
        label: "DiffSBDD",
        note: [
          "比较所选候选分子的分子量、脂溶性等结构性质。",
          "Compare molecular weight, lipophilicity and other descriptors for selected candidates.",
        ],
      },
    ],
  },
  {
    id: "method.diffsbdd.export",
    label: ["候选导出", "Export candidates"],
    default: "diffsbdd.export",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "diffsbdd.export",
        label: "DiffSBDD",
        note: [
          "导出明确候选集合。",
          "Export an explicitly selected candidate collection.",
        ],
      },
    ],
  },
  {
    id: "method.experimental.evidence",
    label: [
      "实验数据与候选比较",
      "Experimental evidence and candidate comparison",
    ],
    default: "experimental.evidence",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "experimental.evidence",
        label: "X-DDE",
        note: [
          "导入实测终点、单位、实验条件和重复，关联确切的分子版本。",
          "Import reported endpoints, units, conditions and replicates linked to exact material versions.",
        ],
      },
    ],
  },
  {
    id: "method.regions",
    label: ["定义完整分子的区域", "Define full-molecule regions"],
    default: "regions",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "regions",
        label: "X-DDE / RDKit",
        note: [
          "在真实原子身份上标记固定核心、结合端、连接区和载荷；区域可重叠并复用。",
          "Annotate overlapping cores, binders, linkers and payloads using native atom identities.",
        ],
      },
    ],
  },
  {
    id: "method.workflows",
    label: ["研究计划与连续任务", "Research plans and task workflows"],
    default: "workflows",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "workflows",
        label: "X-DDE",
        note: [
          "组合真实任务、声明依赖，保留每一步的输入与输出版本。",
          "Combine real tasks with dependencies and retain each step's input/output versions.",
        ],
      },
    ],
  },
  {
    id: "method.p2rank.detect",
    label: ["发现多个候选口袋", "Discover candidate protein pockets"],
    default: "p2rank.detect",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "p2rank.detect",
        label: "P2Rank",
        note: [
          "使用 P2Rank 预测蛋白位点，比较多个候选位点及模型评分。",
          "Predict protein sites with P2Rank and retain multiple hypotheses and native scores.",
        ],
      },
    ],
  },
  {
    id: "method.gnina.dock",
    label: ["探索分子结合模式", "Explore molecular binding poses"],
    default: "gnina.dock",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "gnina.dock",
        label: "GNINA",
        note: [
          "在明确受体与搜索区域中保留多个原生姿势。",
          "Retain multiple native poses for an explicit receptor and search region.",
        ],
      },
    ],
  },
  {
    id: "method.gnina.score",
    label: ["评估已有结合姿势", "Score an existing pose"],
    default: "gnina.score",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "gnina.score",
        label: "GNINA",
        note: [
          "确认坐标参照后计算原生评分，不改变姿势。",
          "Score a confirmed receptor-frame pose without moving it.",
        ],
      },
    ],
  },
  {
    id: "method.gnina.minimize",
    label: ["局部最小化结合姿势", "Locally minimize a binding pose"],
    default: "gnina.minimize",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "gnina.minimize",
        label: "GNINA",
        note: [
          "保留原姿势并生成局部最小化结果；不是充分诱导契合。",
          "Retain the original and produce a local minimum; not full induced fit.",
        ],
      },
    ],
  },
  {
    id: "method.chemistry.states",
    label: ["准备分子状态与构象", "Prepare molecular states and conformers"],
    default: "chemistry.states",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "chemistry.states",
        label: "RDKit + Dimorphite-DL",
        note: [
          "按 pH、互变和立体条件准备有来源的状态及游离三维构象。",
          "Prepare traceable pH/tautomer/stereo states and free three-dimensional conformers.",
        ],
      },
    ],
  },
  {
    id: "method.biopython.ensemble",
    label: ["对齐多个受体构象", "Align receptor conformations"],
    default: "biopython.ensemble",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "biopython.ensemble",
        label: "Biopython",
        note: [
          "复用已有蛋白结构，对齐到参照结构并保留对应和质量记录。",
          "Align existing protein structures to a reference with correspondence and quality evidence.",
        ],
      },
    ],
  },
  {
    id: "method.pose_exploration",
    label: ["多受体与状态姿势探索", "Multi-receptor/state pose exploration"],
    default: "pose_exploration",
    default_basis: [
      "当前唯一接入的方法，已默认选中。",
      "The only integrated method is selected by default.",
    ],
    options: [
      {
        id: "pose_exploration",
        label: "X-DDE / GNINA",
        note: [
          "组合真实位点、受体、分子状态和初始化，保留多个原生姿势及来源。",
          "Combine actual sites, receptors, chemical states and initializations; retain multiple native pose hypotheses and provenance.",
        ],
      },
    ],
  },
] as const;
