// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const defaults = {
  reference_index: 0,
  minimum_pairs: 8,
  minimum_identity: 1.0,
  minimum_coverage: 0.7,
  maximum_rmsd_angstrom: 3.0,
  require_complete_backbone: true,
  cpu: 1,
  memory_mib: 2048,
};
export const selectionDefaults = {
  model_index: 0,
  chains: [],
  profile: "unspecified",
  chain_pairs: [],
  residue_pairs: [],
};
export const schema = {
  additionalProperties: false,
  properties: {
    reference_index: {
      default: 0,
      maximum: 15,
      minimum: 0,
      title: "Reference Index",
      type: "integer",
    },
    minimum_pairs: {
      default: 8,
      maximum: 5000,
      minimum: 3,
      title: "Minimum Pairs",
      type: "integer",
    },
    minimum_identity: {
      default: 1.0,
      maximum: 1.0,
      minimum: 0.5,
      title: "Minimum Identity",
      type: "number",
    },
    minimum_coverage: {
      default: 0.7,
      maximum: 1.0,
      minimum: 0.1,
      title: "Minimum Coverage",
      type: "number",
    },
    maximum_rmsd_angstrom: {
      default: 3.0,
      maximum: 30,
      minimum: 0.1,
      title: "Maximum Rmsd Angstrom",
      type: "number",
    },
    require_complete_backbone: {
      default: true,
      title: "Require Complete Backbone",
      type: "boolean",
    },
    cpu: {
      default: 1,
      maximum: 2,
      minimum: 1,
      title: "Cpu",
      type: "integer",
    },
    memory_mib: {
      default: 2048,
      maximum: 8192,
      minimum: 512,
      title: "Memory Mib",
      type: "integer",
    },
  },
  title: "EnsembleOptions",
  type: "object",
} as const;
export const selectionSchema = {
  $defs: {
    ChainPair: {
      additionalProperties: false,
      properties: {
        reference: {
          maxLength: 8,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f\\x7f]+$",
          title: "Reference",
          type: "string",
        },
        moving: {
          maxLength: 8,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f\\x7f]+$",
          title: "Moving",
          type: "string",
        },
      },
      required: ["reference", "moving"],
      title: "ChainPair",
      type: "object",
    },
    ResidueAddress: {
      additionalProperties: false,
      properties: {
        chain: {
          maxLength: 8,
          minLength: 1,
          pattern: "^[^\\x00-\\x1f\\x7f]+$",
          title: "Chain",
          type: "string",
        },
        number: {
          maximum: 999999,
          minimum: -99999,
          title: "Number",
          type: "integer",
        },
        insertion_code: {
          default: "",
          maxLength: 1,
          pattern: "^[A-Za-z0-9]?$",
          title: "Insertion Code",
          type: "string",
        },
      },
      required: ["chain", "number"],
      title: "ResidueAddress",
      type: "object",
    },
    ResiduePair: {
      additionalProperties: false,
      properties: {
        reference: {
          $ref: "#/$defs/ResidueAddress",
        },
        moving: {
          $ref: "#/$defs/ResidueAddress",
        },
      },
      required: ["reference", "moving"],
      title: "ResiduePair",
      type: "object",
    },
  },
  additionalProperties: false,
  properties: {
    model_index: {
      default: 0,
      maximum: 99,
      minimum: 0,
      title: "Model Index",
      type: "integer",
    },
    chains: {
      default: [],
      items: {
        type: "string",
      },
      maxItems: 16,
      title: "Chains",
      type: "array",
    },
    profile: {
      default: "unspecified",
      enum: ["unspecified", "experimental", "predicted"],
      title: "Profile",
      type: "string",
    },
    chain_pairs: {
      default: [],
      items: {
        $ref: "#/$defs/ChainPair",
      },
      maxItems: 16,
      title: "Chain Pairs",
      type: "array",
    },
    residue_pairs: {
      default: [],
      items: {
        $ref: "#/$defs/ResiduePair",
      },
      maxItems: 5000,
      title: "Residue Pairs",
      type: "array",
    },
  },
  title: "MemberSelection",
  type: "object",
} as const;
