// Generated by scripts/generate-capability-catalog.py; edit backend authority.
export const nativeDefaults = {
  boltz: {
    kind: "boltz",
    samples: 3,
    recycling_steps: 3,
    sampling_steps: 200,
    affinity: false,
  },
  reinvent: {
    kind: "reinvent",
    mode: "analogues",
    candidates: 50,
    optimization_steps: 25,
    molecular_weight: [200, 550],
    logp: [0, 5],
  },
  ligandmpnn: {
    kind: "ligandmpnn",
    candidates: 8,
    temperature: 0.1,
    pack_sidechains: true,
  },
  boltzgen: {
    kind: "boltzgen",
    modality: "protein",
    length: [80, 120],
    candidates: 20,
    retain: 5,
    scaffold_chain: null,
  },
  openmm: {
    kind: "openmm",
    ph: 7.4,
    iterations: 500,
    restrain_backbone: true,
    restraint_kj_mol_nm2: 1000,
  },
  apbs: {
    kind: "apbs",
    ph: 7.4,
    salt_molar: 0.15,
    grid: 97,
    temperature_kelvin: 298.15,
  },
  chemprop: {
    kind: "chemprop",
    mode: "train",
    activity_property: "pIC50",
    activity_unit: "pIC50",
    epochs: 30,
    model_job: null,
    model_sha256: null,
  },
  plip: {
    kind: "plip",
  },
} as const;
