"""Generate UI inventory and defaults from the backend, using the locked formatter."""

import argparse
import json
import subprocess
from pathlib import Path

from opendde_workbench.admet.manifest import MAX_HEAVY_ATOMS, MAX_INPUT_BYTES, MAX_RECORDS, VERSIONS
from opendde_workbench.admet.options import AdmetOptions
from opendde_workbench.antibodies.options import NumberingOptions
from opendde_workbench.capabilities import frontend_catalogue
from opendde_workbench.capabilities.modalities import modality_catalogue
from opendde_workbench.chemistry.options import StateOptions
from opendde_workbench.chemistry.screen_options import ScreenOptions
from opendde_workbench.diffsbdd.manifest import MODELS
from opendde_workbench.diffsbdd.options import DiffOptions
from opendde_workbench.diffsbdd.quality import CoreVerification
from opendde_workbench.docking.options import DockingOptions
from opendde_workbench.humanization.manifest import MAX_RECORDS as HUMANIZATION_MAX_RECORDS
from opendde_workbench.humanization.manifest import VERSIONS as HUMANIZATION_VERSIONS
from opendde_workbench.humanization.options import HumanizationOptions
from opendde_workbench.integrations.options import (
    BoltzGenPayload,
    BoltzPayload,
    ChempropPayload,
    ElectrostaticsPayload,
    InteractionPayload,
    LigandMPNNPayload,
    RefinementPayload,
    ReinventPayload,
)
from opendde_workbench.pose_ensembles.contracts import ExplorationOptions
from opendde_workbench.quality.options import QualityOptions
from opendde_workbench.receptors.selection import EnsembleOptions, MemberSelection
from opendde_workbench.research.constraint_contract import ConstraintSet, SpatialBoundsCondition
from opendde_workbench.research.regions import REGION_ROLES
from opendde_workbench.sites.contracts import SiteOptions


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    formatter = root / "frontend/node_modules/prettier/bin/prettier.cjs"
    if not formatter.is_file():
        raise SystemExit("Install locked frontend dependencies with npm ci before generation.")
    header = "// Generated by scripts/generate-capability-catalog.py; edit backend authority.\n"
    files = {
        "integrations/generated.ts": header
        + "export const nativeDefaults = "
        + json.dumps(
            {
                name: {
                    key: value["default"]
                    for key, value in model.model_json_schema()["properties"].items()
                    if "default" in value
                }
                for name, model in {
                    "boltz": BoltzPayload,
                    "reinvent": ReinventPayload,
                    "ligandmpnn": LigandMPNNPayload,
                    "boltzgen": BoltzGenPayload,
                    "openmm": RefinementPayload,
                    "apbs": ElectrostaticsPayload,
                    "chemprop": ChempropPayload,
                    "plip": InteractionPayload,
                }.items()
            },
            indent=2,
        )
        + " as const;\n",
        "humanization/generated.ts": header
        + "export const humanizationDefaults = "
        + json.dumps(HumanizationOptions().model_dump(mode="json"), indent=2)
        + " as const;\nexport const humanizationVersions = "
        + json.dumps(HUMANIZATION_VERSIONS, indent=2)
        + " as const;\nexport const humanizationMaxRecords = "
        + str(HUMANIZATION_MAX_RECORDS)
        + ";\n",
        "admet/generated.ts": header
        + "export const admetDefaults = "
        + json.dumps(AdmetOptions().model_dump(mode="json"), indent=2)
        + " as const;\nexport const admetVersions = "
        + json.dumps(VERSIONS, indent=2)
        + " as const;\nexport const admetLimits = "
        + json.dumps(
            {
                "maxRecords": MAX_RECORDS,
                "maxHeavyAtoms": MAX_HEAVY_ATOMS,
                "maxInputBytes": MAX_INPUT_BYTES,
            },
            indent=2,
        )
        + " as const;\n",
        "quality/generated.ts": header
        + "export const qualityDefaults = "
        + json.dumps(QualityOptions().model_dump(mode="json"), indent=2)
        + ";\n",
        "antibodies/generated.ts": header
        + "export const numberingDefaults = "
        + json.dumps(NumberingOptions().model_dump(mode="json"), indent=2)
        + ";\n",
        "poses/generated.ts": header
        + "export const defaults = "
        + json.dumps(ExplorationOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const schema = "
        + json.dumps(ExplorationOptions.model_json_schema(), indent=2)
        + " as const;\n",
        "sites/generated.ts": header
        + "export const defaults = "
        + json.dumps(SiteOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const schema = "
        + json.dumps(SiteOptions.model_json_schema(), indent=2)
        + " as const;\n",
        "receptors/generated.ts": header
        + "export const defaults = "
        + json.dumps(EnsembleOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const selectionDefaults = "
        + json.dumps(MemberSelection().model_dump(mode="json"), indent=2)
        + ";\nexport const schema = "
        + json.dumps(EnsembleOptions.model_json_schema(), indent=2)
        + " as const;\nexport const selectionSchema = "
        + json.dumps(MemberSelection.model_json_schema(), indent=2)
        + " as const;\n",
        "chemistry/generated.ts": header
        + "export const defaults = "
        + json.dumps(StateOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const schema = "
        + json.dumps(StateOptions.model_json_schema(), indent=2)
        + " as const;\nexport const screenDefaults = "
        + json.dumps(ScreenOptions().model_dump(mode="json"), indent=2)
        + " as const;\nexport const screenSchema = "
        + json.dumps(ScreenOptions.model_json_schema(), indent=2)
        + " as const;\n",
        "constraints/generated.ts": header
        + "export const constraintSchema = "
        + json.dumps(ConstraintSet.model_json_schema(), ensure_ascii=False, indent=2)
        + " as const;\nexport const outputBoundsDefaults = "
        + json.dumps(
            {
                "tolerance_angstrom": SpatialBoundsCondition.model_fields[
                    "tolerance_angstrom"
                ].default,
                "strength": "hard",
                "weight": 1,
            },
            indent=2,
        )
        + " as const;\n",
        "docking/generated.ts": header
        + "export const defaults = "
        + json.dumps(DockingOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const optionsSchema = "
        + json.dumps(DockingOptions.model_json_schema(), indent=2)
        + " as const;\n",
        "regions/generated.ts": header
        + "export const roles = "
        + json.dumps(REGION_ROLES, ensure_ascii=False, indent=2)
        + " as const;\n",
        "operations/catalog.ts": header
        + "export const modalities = "
        + json.dumps(modality_catalogue(), ensure_ascii=False, indent=2)
        + ' as const;\nexport type ModalityId = (typeof modalities)[number]["id"];\n'
        + "export const tools = "
        + json.dumps(frontend_catalogue(), ensure_ascii=False, indent=2)
        + ' as const;\nexport type ToolId = (typeof tools)[number]["id"];\n',
        "diffsbdd/generated.ts": header
        + "export const defaults = "
        + json.dumps(DiffOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const models = "
        + json.dumps(list(MODELS.values()), indent=2)
        + " as const;\nexport const optionSchema = "
        + json.dumps(DiffOptions.model_json_schema(), indent=2)
        + " as const;\nexport const coreVerificationSchema = "
        + json.dumps(CoreVerification.model_json_schema(), indent=2)
        + " as const;\n",
    }
    for name, body in files.items():
        path = root / "frontend/src" / name
        formatted = subprocess.run(
            ["node", str(formatter), "--parser", "typescript"],
            input=body,
            text=True,
            encoding="utf-8",
            capture_output=True,
            check=True,
        ).stdout
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != formatted:
                raise SystemExit(f"Generated frontend contract is stale: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(formatted, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
