"""Generate UI inventory and defaults from the backend, using the locked formatter."""

import argparse
import json
import subprocess
from pathlib import Path

from opendde_workbench.capabilities import frontend_catalogue
from opendde_workbench.capabilities.modalities import modality_catalogue
from opendde_workbench.diffsbdd.manifest import MODELS
from opendde_workbench.diffsbdd.options import DiffOptions
from opendde_workbench.docking.options import DockingOptions
from opendde_workbench.research.regions import REGION_ROLES


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    formatter = root / "frontend/node_modules/prettier/bin/prettier.cjs"
    if not formatter.is_file():
        raise SystemExit("Install locked frontend dependencies with npm ci before generation.")
    header = "// Generated by scripts/generate-capability-catalog.py; edit backend authority.\n"
    files = {
        "docking/generated.ts": header
        + "export const defaults = "
        + json.dumps(DockingOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const optionsSchema = "
        + json.dumps(DockingOptions.model_json_schema(), indent=2)
        + " as const;\n",
        "regions/generated.ts": header
        + "export const roles = "
        + json.dumps(REGION_ROLES, ensure_ascii=False, indent=2)
        + " as const;\n",
        "operations/catalog.ts": header
        + "export const modalities = "
        + json.dumps(modality_catalogue(), ensure_ascii=False, indent=2)
        + ' as const;\nexport type ModalityId = (typeof modalities)[number]["id"];\n'
        + "export const tools = "
        + json.dumps(frontend_catalogue(), ensure_ascii=False, indent=2)
        + ' as const;\nexport type ToolId = (typeof tools)[number]["id"];\n',
        "diffsbdd/generated.ts": header
        + "export const defaults = "
        + json.dumps(DiffOptions().model_dump(mode="json"), indent=2)
        + ";\nexport const models = "
        + json.dumps(list(MODELS.values()), indent=2)
        + " as const;\nexport const optionSchema = "
        + json.dumps(DiffOptions.model_json_schema(), indent=2)
        + " as const;\n",
    }
    for name, body in files.items():
        path = root / "frontend/src" / name
        formatted = subprocess.run(
            ["node", str(formatter), "--parser", "typescript"],
            input=body,
            text=True,
            capture_output=True,
            check=True,
        ).stdout
        if args.check:
            if not path.is_file() or path.read_text() != formatted:
                raise SystemExit(f"Generated frontend contract is stale: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(formatted, encoding="utf-8")


if __name__ == "__main__":
    main()
