"""Bundle locked upstream layout CSS without permitting runtime inline style injection."""

import argparse
import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "frontend/node_modules/plotly.js-cartesian-dist-min"
OUTPUT = ROOT / "frontend/src/simulations/plotly-native.css"


def generate():
    version = json.loads((PACKAGE / "package.json").read_text(encoding="utf-8"))["version"]
    if version != "4.1.2":
        raise ValueError("Review the native stylesheet when updating Plotly.")
    source = (PACKAGE / "plotly-cartesian.min.js").read_text(encoding="utf-8")
    marker = source.index('"X .main-svg"')
    start, end = source.rfind("{", 0, marker), source.index("}", marker)
    pairs = re.findall(
        r"""("(?:\\.|[^"\\])*")\s*:\s*("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')""",
        source[start : end + 1],
    )
    rules = [(json.loads(key), ast.literal_eval(value)) for key, value in pairs]
    if len(rules) < 50 or not any(key == "X .main-svg .draglayer" for key, _ in rules):
        raise ValueError("The locked upstream style dictionary changed.")
    header = (
        "/* Generated by scripts/generate-plotly-css.py from Plotly.js 4.1.2.\n"
        " * Copyright Plotly, Inc. MIT; https://github.com/plotly/plotly.js/blob/v4.1.2/LICENSE\n"
        " * Native layer positioning is required under X-DDE's strict style-src policy.\n"
        " * Do not edit by hand. */\n"
    )
    return (
        header
        + "\n".join(
            key.replace("X", ".js-plotly-plot .plotly").replace("Y", ".plotly-notifier")
            + " { "
            + value
            + " }"
            for key, value in rules
        )
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    css = generate()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != css:
            raise ValueError("Regenerate the reviewed native Plotly stylesheet.")
    else:
        OUTPUT.write_text(css, encoding="utf-8")


if __name__ == "__main__":
    main()
